// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK622W6oztHDreTl_dEx8wn_qdXhsm8Sw',
    appId: '1:261281460648:web:5d951f28d2e73a614cad9d',
    messagingSenderId: '261281460648',
    projectId: 'platinum-goods-469913-s2',
    authDomain: 'platinum-goods-469913-s2.firebaseapp.com',
    storageBucket: 'platinum-goods-469913-s2.firebasestorage.app',
    measurementId: 'G-P2E8C8VR6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOVh5K5qWYgCnwNYp4Fa2knqO78eD0nQI',
    appId: '1:261281460648:android:f989fd43169751f24cad9d',
    messagingSenderId: '261281460648',
    projectId: 'platinum-goods-469913-s2',
    storageBucket: 'platinum-goods-469913-s2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhF3kBP-wPkzGVacezse9kYGEMPdk99Xg',
    appId: '1:261281460648:ios:a434330dfb84549c4cad9d',
    messagingSenderId: '261281460648',
    projectId: 'platinum-goods-469913-s2',
    storageBucket: 'platinum-goods-469913-s2.firebasestorage.app',
    iosBundleId: 'com.example.fluxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK622W6oztHDreTl_dEx8wn_qdXhsm8Sw',
    appId: '1:261281460648:web:6af1ee02c3e3e8204cad9d',
    messagingSenderId: '261281460648',
    projectId: 'platinum-goods-469913-s2',
    authDomain: 'platinum-goods-469913-s2.firebaseapp.com',
    storageBucket: 'platinum-goods-469913-s2.firebasestorage.app',
    measurementId: 'G-TS6WCV7L2H',
  );
}
